log_folder: "logs"

server_config:
  initial_size: 100000
  page_size: 4096
  wal_enabled: false
  durability_mode: "NeverSync"

client_config:
  qps_increment: 10000
  max_qps: 1000000
  qps_tier_duration: 5
  load_type: "ReadDominant"
